---
title: "R htmlwidgets-D3 and Canvas Express"
author: "Ehson Ghandehari"
date: "6/13/2017""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

The purpose of this Markdown document is to utilized some of the R htmlwidgets. In this document the **iris** dataset were used for visualization. We use **pairsD3**, and **canvasXpress** for graphing. 

## Including Plots

```{r fig1, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.cap="</br>**Figure 1:** Presenting the Iris data set in three-dimension pair(faces)."}
library(pairsD3)
data(iris)
require(pairsD3)
pairsD3(iris[,1:4],group=iris[,5])
```

```{r fig2, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.cap="</br>**Figure 2:** Presenting the Iris data based on three variables: Sepal length, sepal width, and petal width."}

library(canvasXpress)
data <- t(iris[,1:4])
varAnnot <- as.matrix(iris[,5])
colnames(varAnnot) <- "Species"
canvasXpress(t(data), varAnnot=varAnnot, graphType='Scatter3D', colorBy='Species')
```
